// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    return {
      formatDate: function(timestamp) {
        var date;

        date = new Date(timestamp);
        return "" + (date.getDate()) + "-" + (date.getMonth()) + "-" + (date.getFullYear());
      },
      isNumber: function(num) {
        return !isNaN(+num);
      },
      formatDecimals: function(num, decimals) {
        var fac;

        fac = Math.pow(10, decimals);
        return Math.round(+num * fac) / fac;
      }
    };
  });

}).call(this);
