// Generated by CoffeeScript 1.6.2
(function() {
  define(['backbone'], function(Backbone) {
    return Backbone.Model.extend({
      complies: function(number, test) {
        return !test.get('error');
      }
    });
  });

}).call(this);
