// Generated by CoffeeScript 1.6.2
(function() {
  define(['backbone'], function(Backbone) {
    return Backbone.Model.extend({
      defaults: {
        sorting: 'date',
        showErrors: true
      }
    });
  });

}).call(this);
