// Generated by CoffeeScript 1.6.2
(function() {
  var Plot2D, element, plot;

  Plot2D = (function() {
    function Plot2D(el) {
      var $el, height, width;

      $el = $(el);
      width = $el.width();
      height = $el.height();
      this.paper = Raphael($el[0], width, height);
    }

    Plot2D.prototype.drawCircleWithOrientation = function(x, y, phi, color) {
      this.drawArrow(x, y, phi);
      return this.drawCircle(x, y, color);
    };

    Plot2D.prototype.drawCircle = function(x, y, color) {
      var circle, radius;

      radius = 3.5;
      circle = this.paper.circle(x, y + .5, radius);
      circle.attr('fill', color);
      return circle.attr('stroke', 'transparent');
    };

    Plot2D.prototype.drawArrow = function(x, y, phi) {
      var head, length, line, pathString;

      length = 15;
      pathString = "M0,.5L" + length + ",.5";
      line = this.paper.path(pathString);
      head = this.drawArrowHead();
      line.transform("t" + x + "," + y + "r" + phi + ",0,.5");
      return head.transform("t" + (x + length) + "," + y + "r" + phi + ",-" + length + ",.5");
    };

    Plot2D.prototype.drawArrowHead = function() {
      var height, path, width, x1, y0, y1;

      height = 4;
      width = 4;
      y0 = -Math.floor(height / 2) - .5;
      y1 = Math.ceil(height / 2) + 1.5;
      x1 = width + .5;
      path = this.paper.path("M.5,.5L.5," + y0 + "L" + x1 + ",.5L.5," + y1 + "L.5,.5");
      path.attr('fill', 'black');
      return path;
    };

    return Plot2D;

  })();

  element = $('#plot');

  plot = new Plot2D(element);

}).call(this);
