// Generated by CoffeeScript 1.6.3
(function() {
  define(['backbone'], function(Backbone) {
    return Backbone.Model.extend({
      defaults: {
        testResults: null
      }
    });
  });

}).call(this);
