// Generated by CoffeeScript 1.6.2
(function() {
  define(['backbone'], function(Backbone) {
    return Backbone.View.extend({
      tagName: 'div',
      className: 'developerCharts',
      render: function() {
        this.$el.html('lololol');
        return this;
      }
    });
  });

}).call(this);
