// Generated by CoffeeScript 1.6.2
(function() {
  require(['backbone'], function(Backbone) {
    Backbone.View.extend({
      tagName: 'div',
      className: 'developerView'
    });
    return {
      renderComponentDevView: function() {
        var componentDevView;

        componentDevView = new ComponentDevView({
          testGroups: testGroups
        });
        $('#componentDevView').html(componentDevView.render().el);
        return $(window).trigger('resize');
      }
    };
  });

}).call(this);
