// Generated by CoffeeScript 1.6.2
(function() {
  define(['backbone', 'templates/sortingOptions'], function(Backbone, sortingOptionsTmpl) {
    return Backbone.View.extend({
      events: {
        'click  input.sort': 'sortingChanged',
        'change #showErrorsChkbx': 'showErrorsChanged'
      },
      render: function() {
        this.$el.html(sortingOptionsTmpl({
          sorting: this.model.get('sorting'),
          showErrors: this.model.get('showErrors')
        }));
        return this;
      },
      sortingChanged: function(e) {
        var input, value;

        input = $(e.currentTarget);
        value = input.val();
        if (value) {
          return this.model.set('sorting', value);
        }
      },
      showErrorsChanged: function(e) {
        var input, value;

        input = $(e.currentTarget);
        value = input.prop('checked');
        return this.model.set('showErrors', value);
      }
    });
  });

}).call(this);
