// Generated by CoffeeScript 1.6.2
(function() {
  define(['backbone', 'models/testDetailLineChart', 'views/lineChart'], function(Backbone, LineChart, LineChartView) {
    return Backbone.View.extend({
      tagName: 'div',
      className: 'testDetailDevChart',
      initialize: function() {
        this.lineChartModel = new LineChart;
        return this.lineChartView = new LineChartView({
          model: this.lineChartModel,
          label: this.options.label,
          unit: this.options.unit
        });
      },
      renderDeltas: function(t, deltas) {
        return this.lineChartModel.updateDeltas(t, deltas);
      },
      render: function() {
        this.$el.html(this.lineChartView.render().el);
        return this;
      },
      renderDataset: function() {}
    });
  });

}).call(this);
