// Generated by CoffeeScript 1.6.3
(function() {
  define(['backbone'], function(Backbone) {
    return Backbone.View.extend({
      options: {
        online: false
      },
      initialize: function() {
        var dfd,
          _this = this;
        dfd = this.query({
          ping: 'onlineCheck'
        });
        return dfd.done(function() {
          console.log('online');
          return _this.options.online = true;
        });
      },
      videoExists: function(filename) {
        var dfd;
        dfd = this.videosExist([filename]);
        return dfd.pipe(function(results) {
          return results[0];
        });
      },
      videosExist: function(filenames) {
        var dfd;
        if (!this.options.online) {
          dfd = $.Deferred();
          dfd.reject('Could not connect to the video server');
        } else {
          dfd = this.query({
            exists: filenames
          });
        }
        return dfd;
      },
      query: function(data) {
        return $.ajax({
          url: '/video',
          crossDomain: true,
          data: data,
          dataType: 'jsonp'
        });
      }
    });
  });

}).call(this);
